import {
  ArrowLeftRight,
  ArrowRightLeft,
  Binary,
  Bomb,
  Bot,
  Braces,
  Calculator,
  Code,
  Coins,
  Combine,
  Cpu,
  DoorOpen,
  Equal,
  Eye,
  EyeOff,
  FileArchive,
  FileDown,
  FileText,
  FileUp,
  Filter,
  Fingerprint,
  FlipHorizontal2,
  FolderInput,
  FunctionSquare,
  Gauge,
  GitBranch,
  Grid2x2,
  Grid3x3,
  Hash,
  Hexagon,
  IterationCw,
  KeyRound,
  Languages,
  Layers,
  Link,
  Link2,
  ListOrdered,
  Lock,
  type LucideIcon,
  Merge,
  Package,
  QrCode,
  RefreshCw,
  Repeat,
  Replace,
  RotateCcw,
  RotateCw,
  Route,
  Ruler,
  ScanEye,
  ScanLine,
  Search,
  Sigma,
  Sparkles,
  Split,
  TableProperties,
  Type,
  VenetianMask,
  Wand2,
  Zap,
} from "lucide-react";

// A distinct icon per module.
const NODE_ICONS: Record<string, LucideIcon> = {
  text_input: Type,
  file_import: FileUp,
  file_output: FileDown,
  text_output: FileText,
  base64_encode: Code,
  base64_decode: Braces,
  base32_encode: Grid2x2,
  base32_decode: Grid2x2,
  base45_encode: Grid3x3,
  base45_decode: Grid3x3,
  base58_encode: Coins,
  base58_decode: Coins,
  base62_encode: Sigma,
  base62_decode: Sigma,
  base85_encode: Hexagon,
  base85_decode: Hexagon,
  base92_encode: Layers,
  base92_decode: Layers,
  hex_encode: Hash,
  hex_decode: Binary,
  url_encode: Link,
  url_decode: Link2,
  rot13: RotateCw,
  xor: Zap,
  xor_bruteforce: Bomb,
  loop_decode: Repeat,
  magic_decode: Wand2,
  qr_encode: QrCode,
  qr_decode: ScanLine,
  reverse: ArrowLeftRight,
  regex_extract: Search,
  text_score: Gauge,
  concat: Combine,
  split: Split,
  length: Ruler,
  replace: Replace,
  switch: GitBranch,
  compare: Equal,
  archive_extract: FileArchive,
  zero_width_decode: ScanEye,
  zero_width_encode: EyeOff,
  hash: Fingerprint,
  hmac: KeyRound,
  radix_convert: ArrowRightLeft,
  to_binary: Binary,
  from_binary: Binary,
  to_decimal: Calculator,
  from_decimal: Calculator,
  encode_text: Languages,
  decode_text: Languages,
  aes: Lock,
  rc4: KeyRound,
  vigenere: TableProperties,
  affine: FunctionSquare,
  atbash: FlipHorizontal2,
  rot47: RotateCcw,
  logic: Cpu,
  switch_case: Route,
  gate: DoorOpen,
  range: ListOrdered,
  map: IterationCw,
  filter_list: Filter,
  join_list: Merge,
  iterate: RefreshCw,
  ai_judge: Bot,
  ai_vision: Eye,
};

const CATEGORY_ICONS: Record<string, LucideIcon> = {
  输入输出: FolderInput,
  "编码/加密": KeyRound,
  文本处理: Type,
  "控制/逻辑": GitBranch,
  压缩包: Package,
  隐写术: VenetianMask,
  "哈希/摘要": Fingerprint,
  进制转换: Binary,
  加密解密: Lock,
  字符编码: Languages,
  AI: Sparkles,
};

export function nodeIcon(id: string, category?: string): LucideIcon {
  return NODE_ICONS[id] ?? (category ? CATEGORY_ICONS[category] : undefined) ?? Braces;
}

export function categoryIcon(category: string): LucideIcon {
  return CATEGORY_ICONS[category] ?? Braces;
}
