/**
 * Short, human-readable descriptions for every built-in node, shown in the module
 * library. Keyed by descriptor id. Kept in the frontend so we don't have to touch
 * ~90 Rust files; falls back to the display name when an id is missing.
 */
export const NODE_DESCRIPTIONS: Record<string, string> = {
  // 输入输出
  text_input: "输入一段文本，作为流程的起点。",
  text_output: "显示上游节点产出的文本结果。",
  file_import: "从磁盘导入文件，输出原始字节。",
  file_output: "把字节数据保存为文件。",
  image_input: "选择图片，输出字节与预览。",

  // 编码/加密（各类编码）
  base16_encode: "Base16（十六进制）编码。",
  base16_decode: "Base16（十六进制）解码。",
  base32_encode: "Base32 编码（RFC 4648）。",
  base32_decode: "Base32 解码。",
  base45_encode: "Base45 编码（常见于二维码）。",
  base45_decode: "Base45 解码。",
  base58_encode: "Base58 编码（比特币字母表，去易混字符）。",
  base58_decode: "Base58 解码。",
  base62_encode: "Base62 编码（0-9A-Za-z）。",
  base62_decode: "Base62 解码。",
  base64_encode: "Base64 编码，最常见的编码。",
  base64_decode: "Base64 解码，拿到乱码先试它。",
  base85_encode: "Base85 / Ascii85 编码。",
  base85_decode: "Base85 / Ascii85 解码。",
  base92_encode: "Base92 编码。",
  base92_decode: "Base92 解码。",
  hex_encode: "转十六进制字符串。",
  hex_decode: "十六进制字符串还原为字节。",
  url_encode: "URL 百分号编码。",
  url_decode: "URL 百分号解码。",
  rot13: "ROT13 字母表轮转 13 位。",
  rot47: "ROT47 可见 ASCII 轮转 47 位。",
  morse_encode: "文本转摩尔斯电码。",
  morse_decode: "摩尔斯电码转文本。",
  bacon_encode: "培根密码编码（a/b 五元组）。",
  bacon_decode: "培根密码解码。",
  a1z26_encode: "字母转序号 A=1…Z=26。",
  a1z26_decode: "序号 A1Z26 还原为字母。",
  braille_encode: "文本转盲文点字。",
  braille_decode: "盲文点字转文本。",
  html_entity_encode: "转 HTML 实体（&lt; 等）。",
  html_entity_decode: "HTML 实体还原为字符。",
  unicode_escape: "转 Unicode \\u 转义序列。",
  unicode_unescape: "\\u 转义还原为字符。",
  to_hexdump: "生成 hexdump（含偏移与 ASCII）。",
  from_hexdump: "从 hexdump 还原字节。",
  quoted_printable_encode: "Quoted-Printable 编码。",
  quoted_printable_decode: "Quoted-Printable 解码。",
  bitwise: "按位运算：XOR/AND/OR/移位。",
  xor: "与密钥按字节异或。",
  xor_bruteforce: "单字节 XOR 爆破，按可读性排序取最优。",
  rotate_bytes: "字节位旋转 ROL/ROR。",
  magic_decode: "自动识别编码并逐层解码，直到出现 flag。",
  loop_decode: "对同一种编码反复解码，处理套娃嵌套。",
  qr_encode: "把文本编码成二维码并预览。",
  qr_decode: "识别二维码/条码里的内容。",

  // 进制转换
  to_binary: "文本转二进制 0/1 串。",
  from_binary: "二进制 0/1 串转文本。",
  to_octal: "文本转八进制。",
  from_octal: "八进制转文本。",
  to_decimal: "文本转十进制。",
  from_decimal: "十进制转文本。",
  to_charcode: "字符转码点（可选进制/分隔符）。",
  from_charcode: "码点转字符。",
  radix_convert: "任意进制（2–36）之间互转。",

  // 字符编码
  encode_text: "按字符集（UTF-8/GBK/Big5…）编码为字节。",
  decode_text: "把字节按字符集解码为文本。",

  // 加密解密（对称/古典/非对称）
  aes: "AES 加解密（CBC/ECB/CTR）。",
  des: "DES / 3DES 加解密。",
  blowfish: "Blowfish 加解密。",
  rc4: "RC4 流密码加解密。",
  chacha20: "ChaCha20 / XChaCha20 流密码。",
  salsa20: "Salsa20 流密码。",
  vigenere: "维吉尼亚多表密码。",
  affine: "仿射密码（ax+b）。",
  atbash: "Atbash 字母表反射（a↔z）。",
  caesar: "凯撒位移密码。",
  rail_fence_encode: "栅栏（zigzag）密码加密。",
  rail_fence_decode: "栅栏密码解密。",
  substitution: "单表替换密码。",
  bifid_encode: "Bifid 联合密码加密。",
  bifid_decode: "Bifid 联合密码解密。",
  playfair_encode: "Playfair 双字母密码加密。",
  playfair_decode: "Playfair 双字母密码解密。",
  enigma: "恩尼格玛机（M3，可配转子/插线板）。",
  adfgvx: "ADFGVX / ADFGX 密码。",
  rsa_params: "由 p、q、e 算出 n、φ(n) 与私钥 d。",
  rsa_decrypt: "RSA 解密（给定 n、d 或 p、q）。",
  pgp_dearmor: "PGP ASCII 装甲解甲为二进制。",
  pgp_enarmor: "二进制打包成 PGP ASCII 装甲。",
  pgp_decrypt: "用私钥+口令解密 PGP 消息。",

  // 哈希/摘要
  hash: "多算法哈希（MD5/SHA/SM3/CRC…）。",
  hmac: "HMAC 消息认证码。",
  bcrypt: "bcrypt 哈希或口令校验。",
  hash_crack: "字典爆破哈希，逐词比对求明文（含加盐）。",

  // 压缩包
  compress: "Gzip / Zlib / Raw Deflate 压缩。",
  archive_extract: "解压 zip/7z/rar/gz/tar（支持密码）。",

  // 隐写术
  zero_width_encode: "把秘密藏进不可见的零宽字符。",
  zero_width_decode: "从零宽字符还原秘密（自动识别）。",
  lsb_extract: "读取图片 RGB 最低位平面拼回数据。",
  stegcloak_hide: "StegCloak 把秘密藏进文本零宽字符。",
  stegcloak_reveal: "StegCloak 解出文本里的秘密（可带密码）。",
  whitespace_encode: "SNOW 空白隐写（空格/制表位）。",
  whitespace_decode: "还原空白隐写。",
  imagein_extract: "imageIN（图影）从图片提取藏的文件。",
  imagein_embed: "imageIN 把文件藏进图片位平面。",
  cloacked_pixel_extract: "cloacked-pixel 解出 LSB+AES 载荷。",
  cloacked_pixel_embed: "cloacked-pixel 加密后藏进 LSB。",
  imagemask_text_extract: "ImageMask 提取藏在图片里的文本。",
  imagemask_file_extract: "ImageMask 提取藏在图片里的文件。",
  imagemask_text_embed: "ImageMask 把文本藏进图片。",
  imagemask_file_embed: "ImageMask 把文件藏进图片。",
  bmp_padding_extract: "读取 BMP 每行 4 字节对齐的填补字节。",
  bmp_padding_embed: "把数据藏进 BMP 行填补字节。",
  psimage_extract: "Invoke-PSImage 还原藏的 PowerShell 脚本。",
  psimage_embed: "Invoke-PSImage 把脚本藏进像素低位。",
  stegpy_extract: "stegpy LSB 提取（stegv3 容器）。",
  stegpy_embed: "stegpy LSB 隐写文本/文件。",
  braintools_decode: "解 Brainloller/Braincopter 图为 Brainfuck 并可运行。",
  pixeljihad_extract: "PixelJihad 从伪随机位置提取秘密。",
  pixeljihad_embed: "PixelJihad 把文本藏进图片。",

  // 图像处理
  image_blend: "两图混合（XOR/差值/叠加等）。",
  image_concat: "横向/纵向拼接两张图。",
  channel_extract: "提取单个颜色通道。",
  channel_split: "拆成 R/G/B/A 独立通道。",
  channel_merge: "把多个通道合并为一张图。",
  channel_swap: "交换颜色通道顺序。",
  bit_plane: "提取某通道的单个位平面。",
  grayscale: "转为灰度图。",
  image_invert: "图像反相（负片）。",
  threshold: "二值化（支持 Otsu 自动阈值）。",
  brightness_contrast: "调整亮度与对比度。",
  gamma: "伽马校正。",
  hist_equalize: "直方图均衡增强对比。",
  edge_detect: "Sobel 边缘检测。",
  image_xor: "图像与常量按位异或。",
  image_transform: "旋转 / 翻转。",
  image_crop: "裁剪出一块区域。",
  image_resize: "缩放到指定尺寸。",
  image_info: "查看尺寸、格式等信息。",
  image_convert: "转换图片格式（PNG/JPEG/BMP/GIF）。",
  colorspace_extract: "提取 HSV/YCbCr 分量。",
  image_diff: "高亮两张图的差异。",
  gif_frame: "取出 GIF 的某一帧。",
  gif_sprite: "把 GIF 各帧铺成序列图。",
  dft_spectrum: "二维 FFT 频谱（对数幅度）。",
  connected_components: "连通域标记。",
  morphology: "形态学：膨胀/腐蚀/开闭运算。",
  template_match: "在图中匹配模板位置。",
  png_fix: "CRC 爆破修复被改的 PNG 宽高。",
  blind_watermark: "FFT 频域盲水印显现。",
  bits_to_image: "0/1 文本渲染成黑白图。",
  image_to_bits: "图像二值化为 0/1 文本。",
  pixel_extract: "导出像素值（十进制/十六进制）。",
  values_to_image: "像素值重建成图片。",

  // 文本处理
  reverse: "反转字符串。",
  change_case: "大小写转换。",
  remove_whitespace: "去除空白字符。",
  sort_lines: "按行排序。",
  unique_lines: "行去重（可统计次数）。",
  substring: "截取子串。",
  regex_replace: "正则替换。",
  regex_extract: "正则提取匹配项。",
  pad_lines: "把每行补齐到指定宽度。",
  concat: "拼接两段文本。",
  split: "按分隔符分割文本。",
  length: "计算文本长度。",
  replace: "查找替换。",
  text_score: "文本可读性打分。",

  // 控制/逻辑
  switch: "按条件在两个输入间二选一。",
  switch_case: "按选择器走多路分支。",
  selector: "输出一个常量值。",
  compare: "比较两个值（==/>/< 等）。",
  logic: "逻辑运算 AND/OR/NOT/XOR。",
  gate: "条件成立才放行，否则拦截。",
  range: "生成数值序列。",
  map: "对列表逐项做同一操作。",
  filter_list: "按正则过滤列表。",
  join_list: "把列表合并成文本。",
  iterate: "反复应用操作直到命中正则（while）。",

  // 工具/分析
  entropy: "计算香农熵，判断是否加密/压缩。",
  char_frequency: "统计字符出现频率。",
  defang: "Defang/Refang IOC（网址/IP 转义）。",
  jwt_decode: "解码 JWT 的头部与载荷。",
  json_format: "JSON 美化 / 压缩。",
  from_timestamp: "时间戳转日期。",
  to_timestamp: "日期转时间戳。",
  detect_file_type: "按魔数识别真实文件类型。",
  extract: "提取 IP/邮箱/URL/MAC/flag 等。",
  exif_extract: "读取图片 EXIF 元数据。",

  // AI
  ai_judge: "让 AI 判断/评估内容。",
  ai_vision: "让 AI 识别图片内容。",
};
