import {
  Activity,
  AlignJustify,
  Archive,
  ArrowLeftRight,
  ArrowRightLeft,
  ArrowUpDown,
  BarChart3,
  Binary,
  CaseSensitive,
  CircleDot,
  CircuitBoard,
  Clock,
  CodeXml,
  Eraser,
  Fence,
  FileJson,
  FileSearch,
  Fish,
  Grip,
  KeySquare,
  ListChecks,
  ListFilter,
  LockKeyhole,
  RadioTower,
  Scissors,
  ShieldAlert,
  Shuffle,
  SlidersHorizontal,
  SquareStack,
  Superscript,
  Table,
  Waves,
  Wind,
  Wrench,
  Asterisk,
  AudioLines,
  AudioWaveform,
  Music,
  Phone,
  Aperture,
  Blend,
  Bomb,
  Bot,
  Boxes,
  Braces,
  Component,
  Contrast,
  Crop,
  Crosshair,
  Diff,
  Film,
  ImageDown,
  Pipette,
  Info,
  Palette,
  Scaling,
  SunMedium,
  Camera,
  Cog,
  Image,
  ShieldCheck,
  ShieldMinus,
  ShieldPlus,
  Table2,
  Calculator,
  Code,
  Coins,
  Combine,
  Cpu,
  DoorOpen,
  Equal,
  Eye,
  EyeOff,
  FileArchive,
  FileDown,
  FileText,
  FileUp,
  Filter,
  Globe,
  List,
  Fingerprint,
  FlipHorizontal2,
  FolderInput,
  FunctionSquare,
  Gauge,
  GitBranch,
  Grid2x2,
  Grid3x3,
  Hash,
  Hexagon,
  IterationCw,
  KeyRound,
  Languages,
  Layers,
  LayoutGrid,
  Link,
  Link2,
  ListOrdered,
  Lock,
  type LucideIcon,
  Merge,
  Package,
  QrCode,
  RefreshCw,
  Repeat,
  Replace,
  RotateCcw,
  RotateCw,
  Route,
  Ruler,
  Mail,
  MailOpen,
  Orbit,
  ScanEye,
  ScanLine,
  ScanText,
  Search,
  Sigma,
  Sparkles,
  Split,
  TableProperties,
  Type,
  VenetianMask,
  Wand2,
  Zap,
} from "lucide-react";

// A distinct icon per module.
const NODE_ICONS: Record<string, LucideIcon> = {
  text_input: Type,
  file_import: FileUp,
  file_output: FileDown,
  image_input: Image,
  text_output: FileText,
  base64_encode: Code,
  base64_decode: Braces,
  base32_encode: Grid2x2,
  base32_decode: Grid2x2,
  base45_encode: Grid3x3,
  base45_decode: Grid3x3,
  base58_encode: Coins,
  base58_decode: Coins,
  base62_encode: Sigma,
  base62_decode: Sigma,
  base85_encode: Hexagon,
  base85_decode: Hexagon,
  base92_encode: Layers,
  base92_decode: Layers,
  hex_encode: Hash,
  hex_decode: Binary,
  url_encode: Link,
  url_decode: Link2,
  rot13: RotateCw,
  xor: Zap,
  xor_bruteforce: Bomb,
  hash_crack: Bomb,
  password_crack: Bomb,
  http_request: Globe,
  string_match: Filter,
  archive_list: List,
  loop_decode: Repeat,
  magic_decode: Wand2,
  qr_encode: QrCode,
  qr_decode: ScanLine,
  reverse: ArrowLeftRight,
  regex_extract: Search,
  text_score: Gauge,
  concat: Combine,
  split: Split,
  length: Ruler,
  replace: Replace,
  switch: GitBranch,
  compare: Equal,
  archive_extract: FileArchive,
  zero_width_decode: ScanEye,
  text_blind_watermark: EyeOff,
  guofei_bwm_extract: Fingerprint,
  zero_width_encode: EyeOff,
  stegcloak_hide: LockKeyhole,
  stegcloak_reveal: KeyRound,
  whitespace_encode: Wind,
  whitespace_decode: AlignJustify,
  imagein_extract: ImageDown,
  imagein_embed: FileUp,
  cloacked_pixel_extract: KeyRound,
  cloacked_pixel_embed: LockKeyhole,
  imagemask_text_extract: ScanText,
  imagemask_file_extract: FileDown,
  imagemask_text_embed: FileText,
  imagemask_file_embed: FileUp,
  bmp_padding_extract: AlignJustify,
  bmp_padding_embed: AlignJustify,
  psimage_extract: FileText,
  psimage_embed: FileUp,
  stegpy_extract: Binary,
  stegpy_embed: Image,
  braintools_decode: Binary,
  pixeljihad_extract: Shuffle,
  pixeljihad_embed: Shuffle,
  hash: Fingerprint,
  hmac: KeyRound,
  radix_convert: ArrowRightLeft,
  to_binary: Binary,
  from_binary: Binary,
  to_decimal: Calculator,
  from_decimal: Calculator,
  encode_text: Languages,
  decode_text: Languages,
  aes: Lock,
  rc4: KeyRound,
  vigenere: TableProperties,
  affine: FunctionSquare,
  atbash: FlipHorizontal2,
  rot47: RotateCcw,
  logic: Cpu,
  switch_case: Route,
  selector: ListChecks,
  gate: DoorOpen,
  range: ListOrdered,
  map: IterationCw,
  filter_list: Filter,
  join_list: Merge,
  iterate: RefreshCw,
  change_case: CaseSensitive,
  remove_whitespace: Eraser,
  sort_lines: ArrowUpDown,
  unique_lines: ListFilter,
  substring: Scissors,
  regex_replace: Replace,
  pad_lines: AlignJustify,
  caesar: SlidersHorizontal,
  rail_fence_encode: Fence,
  rail_fence_decode: Fence,
  des: LockKeyhole,
  blowfish: Fish,
  chacha20: Waves,
  salsa20: Wind,
  morse_encode: RadioTower,
  morse_decode: RadioTower,
  bacon_encode: SquareStack,
  bacon_decode: SquareStack,
  a1z26_encode: Hash,
  a1z26_decode: Hash,
  html_entity_encode: CodeXml,
  html_entity_decode: CodeXml,
  unicode_escape: Superscript,
  unicode_unescape: Superscript,
  to_hexdump: Table,
  from_hexdump: Table,
  to_octal: Grip,
  from_octal: Grip,
  entropy: Activity,
  char_frequency: BarChart3,
  defang: ShieldAlert,
  jwt_decode: KeySquare,
  bitwise: CircuitBoard,
  compress: Archive,
  json_format: FileJson,
  substitution: Shuffle,
  braille_encode: CircleDot,
  braille_decode: CircleDot,
  from_timestamp: Clock,
  to_timestamp: Clock,
  rsa_params: KeyRound,
  rsa_decrypt: KeyRound,
  bifid_encode: Grid3x3,
  bifid_decode: Grid3x3,
  playfair_encode: LayoutGrid,
  playfair_decode: LayoutGrid,
  detect_file_type: FileSearch,
  image_blend: Blend,
  image_concat: Combine,
  channel_merge: Merge,
  channel_extract: Layers,
  channel_split: Split,
  channel_swap: Shuffle,
  bit_plane: Binary,
  grayscale: Contrast,
  image_invert: Palette,
  threshold: SlidersHorizontal,
  brightness_contrast: SunMedium,
  gamma: Aperture,
  hist_equalize: BarChart3,
  edge_detect: ScanLine,
  image_xor: Zap,
  image_transform: RotateCw,
  image_crop: Crop,
  image_resize: Scaling,
  image_info: Info,
  image_convert: ImageDown,
  colorspace_extract: Pipette,
  image_diff: Diff,
  gif_frame: Film,
  gif_sprite: LayoutGrid,
  dft_spectrum: Waves,
  connected_components: Component,
  morphology: SquareStack,
  template_match: Crosshair,
  png_fix: Wrench,
  jpg_fix: Ruler,
  bmp_fix: Scaling,
  zip_repair: FileArchive,
  jwt_crack: KeySquare,
  brainfuck: Braces,
  cryptojs_aes: Lock,
  file_carve: Scissors,
  gif_timing: Clock,
  zip_crc_crack: Bomb,
  zsteg_scan: ScanEye,
  rabbit: KeyRound,
  blind_watermark: Waves,
  blind_watermark_dual: Diff,
  bits_to_image: Grid2x2,
  image_to_bits: Binary,
  pixel_extract: Pipette,
  values_to_image: Grid3x3,
  extract: ScanText,
  rotate_bytes: Orbit,
  to_charcode: Binary,
  from_charcode: Type,
  quoted_printable_encode: Mail,
  quoted_printable_decode: MailOpen,
  bcrypt: Asterisk,
  enigma: Cog,
  adfgvx: Table2,
  exif_extract: Camera,
  lsb_extract: Image,
  pgp_dearmor: ShieldMinus,
  pgp_enarmor: ShieldPlus,
  pgp_decrypt: ShieldCheck,
  ai_judge: Bot,
  ai_vision: Eye,
  audio_info: Music,
  audio_spectrogram: AudioLines,
  wav_lsb: Binary,
  dtmf_decode: Phone,
  deepsound_extract: KeyRound,
};

const CATEGORY_ICONS: Record<string, LucideIcon> = {
  输入输出: FolderInput,
  "编码/加密": KeyRound,
  文本处理: Type,
  "控制/逻辑": GitBranch,
  压缩包: Package,
  隐写术: VenetianMask,
  "哈希/摘要": Fingerprint,
  进制转换: Binary,
  加密解密: Lock,
  字符编码: Languages,
  "工具/分析": Wrench,
  图像处理: Image,
  音频处理: AudioWaveform,
  AI: Sparkles,
  自定义: Boxes,
};

export function nodeIcon(id: string, category?: string): LucideIcon {
  return NODE_ICONS[id] ?? (category ? CATEGORY_ICONS[category] : undefined) ?? Braces;
}

export function categoryIcon(category: string): LucideIcon {
  return CATEGORY_ICONS[category] ?? Braces;
}
